name: MacMonitor
options:
  bundleIdPrefix: com.macmonitor
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  
settings:
  base:
    PRODUCT_NAME: MacMonitor
    PRODUCT_BUNDLE_IDENTIFIER: com.macmonitor.MacMonitor
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
    SUPPORTS_MACCATALYST: false
    DEVELOPMENT_TEAM: ""  # Fill in your Team ID
    CODE_SIGN_STYLE: Automatic
    ENABLE_PREVIEWS: true
    INFOPLIST_FILE: MacMonitor/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    
targets:
  MacMonitor:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - MacMonitor
    info:
      path: MacMonitor/Info.plist
      properties:
        CFBundleDisplayName: Mac Monitor
        CFBundleName: MacMonitor
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
        UIInterfaceOrientation: UIInterfaceOrientationLandscapeLeft
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macmonitor.MacMonitor
        INFOPLIST_FILE: MacMonitor/Info.plist
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: ""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        
  MacMonitorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/MacMonitorTests
    dependencies:
      - target: MacMonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.macmonitor.MacMonitorTests
        
schemes:
  MacMonitor:
    build:
      targets:
        MacMonitor: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MacMonitorTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
